spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - name: CircuitBreaker
              args:
                name: defaultCircuitBreaker
                fallbackUri: forward:/fallback
            - name: Retry
              args:
                retries: 1
                statuses: SERVICE_UNAVAILABLE
                methods: POST
          routes:
            - id: vets-service
              uri: lb://vets-service
              predicates:
                - Path=/api/vet/**
              filters:
                - StripPrefix=2
            - id: visits-service
              uri: lb://visits-service
              predicates:
                - Path=/api/visit/**
              filters:
                - StripPrefix=2
            - id: customers-service
              uri: lb://customers-service
              predicates:
                - Path=/api/customer/**
              filters:
                - StripPrefix=2
            - id: genai-service
              uri: lb://genai-service
              predicates:
                - Path=/api/genai/**
              filters:
                - StripPrefix=2
                - CircuitBreaker=name=genaiCircuitBreaker,fallbackUri=/fallback
  reactor:
    context-propagation: auto
---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888

# Build trigger Tue Jun 16 04:56:33 WCAST 2026
# CI build trigger Tue Jun 16 05:05:24 WCAST 2026
# Rebuild Wed Jun 17 03:43:45 WCAST 2026
# Rebuild trigger Wed Jun 17 03:54:09 WCAST 2026
# Rebuild trigger Wed Jun 17 04:14:53 WCAST 2026
# Rebuild Wed Jun 17 04:28:27 WCAST 2026
# Rebuild Wed Jun 17 04:36:08 WCAST 2026
