spring:
  application:
    name: visits-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}


---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888

# Build trigger Tue Jun 16 04:56:33 WCAST 2026
# CI build trigger Tue Jun 16 05:05:24 WCAST 2026
# Rebuild Wed Jun 17 03:43:45 WCAST 2026
# Rebuild trigger Wed Jun 17 03:54:09 WCAST 2026
# Rebuild trigger Wed Jun 17 04:14:53 WCAST 2026
# Rebuild Wed Jun 17 04:28:27 WCAST 2026
# Rebuild Wed Jun 17 04:36:08 WCAST 2026
# Rebuild Wed Jun 17 10:35:52 WAT 2026
