spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

# Avoid some debugging logs at startup
logging:
  level:
    org:
      springframework:
        boot: INFO
        web: INFO

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888


# Build trigger Tue Jun 16 04:56:33 WCAST 2026
# CI build trigger Tue Jun 16 05:05:24 WCAST 2026
# Rebuild Wed Jun 17 03:43:44 WCAST 2026
# Rebuild trigger Wed Jun 17 03:54:09 WCAST 2026
# Rebuild trigger Wed Jun 17 04:14:53 WCAST 2026
# Rebuild Wed Jun 17 04:28:26 WCAST 2026
