server.port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-petclinic/spring-petclinic-microservices-config
          default-label: main
        # Use the File System Backend to avoid git pulling. Enable "native" profile in the Config Server.
        native:
          searchLocations: file:///${GIT_REPO}


# Build trigger Tue Jun 16 04:56:33 WCAST 2026
# CI build trigger Tue Jun 16 05:05:23 WCAST 2026
# Rebuild Wed Jun 17 03:43:44 WCAST 2026
# Rebuild trigger Wed Jun 17 03:54:09 WCAST 2026
# Rebuild trigger Wed Jun 17 04:14:53 WCAST 2026
# Rebuild Wed Jun 17 04:28:26 WCAST 2026
# Rebuild Wed Jun 17 04:36:08 WCAST 2026
# Rebuild Wed Jun 17 10:35:51 WAT 2026
