spring:
  application:
    name: admin-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}


---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888

# Build trigger Tue Jun 16 04:56:34 WCAST 2026
# CI build trigger Tue Jun 16 05:05:25 WCAST 2026
# Rebuild Wed Jun 17 03:43:45 WCAST 2026
